### ISSUE TITLE
Сверстать Footer

### ISSUE THREAD

**Issue by Nikolskii** [Nikolskii/lubimovka#17]

**Comment by t-kerekesha** [comment]
Проверяй)) только я забыла удалить лишние логотипы, не стала перезаливать, когда будешь сливать, удали, пожалуйста) правильные логотипы без цифр в конце)
[ссылка на ветку](https://github.com/Nikolskii/lubimovka/tree/feature/footer)

**Comment by Nikolskii** [comment]
Очень круто!)) как по мне))
